[package]
name = "sfile2"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "indexer"
path = "src/indexer.rs"

[[bin]]
name = "searcher"
path = "src/searcher.rs"

[dependencies]
walkdir = "2.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
